
###  Get all users
GET http://localhost:3000/users/show
content-type: application/json

### Get user by id

GET http://localhost:3000/users/show/2
content-type: application/json

### Get user by name

GET http://localhost:3000/users/showbyname/LorenzTestUser
content-type: application/json

### Get user if exists    /username/password

GET http://localhost:3000/users/exists/test/test
content-type: application/json

### Create new user

POST http://localhost:3000/users/create
content-type: application/json

{
    "name": "DasIstEinTestUser",
    "password": "DasIstEinTest",
    "anzbilder": "0"
}

### Update user compete

PUT http://localhost:3000/users/update/17
content-type: application/json

{
    "name": "XXsampleXX"
}

### Update username   /oldname/newname

PUT http://localhost:3000/users/updateName/test/test12
content-type: application/json

### Update user password /username/newpassword

PUT http://localhost:3000/users/updatePassword/test/testtest
content-type: application/json

### Update user anzahlBilder /username/newanzahlBilder

PUT http://localhost:3000/users/updatebilder/sample/12
content-type: application/json

### user delete by id
DELETE http://localhost:3000/users/deletebyid/
content-type: application/json

### user delete by username
DELETE http://localhost:3000/users/deletebyname/Hans1
content-type: application/json