DELETE http://localhost:3000/users/delete/21
content-type: application/json


### Zweiter Befehl

POST http://localhost:3000/users/create
content-type: application/json

{
    "name": "xx",
    "password": "xxxxxx",
    "anzbilder": "2"
}

###  
GET http://localhost:3000/users/show
content-type: application/json

###

GET http://localhost:3000/users/show/2
content-type: application/json

###

GET http://localhost:3000/users/showbyname/test
content-type: application/json

### 

GET http://localhost:3000/users/exists/test/test
content-type: application/json


### 

PUT http://localhost:3000/users/update/17
content-type: application/json

{
    "name": "XXsampleXX"
}

###

PUT http://localhost:3000/users/updatePassword/test/test
content-type: application/json
